### ISSUE TITLE
StochSS simulation engines fail on OSX El Capitan

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#537]
The new "System Integrity Protection" (SIP) prevents the StochSS simulation engines (specifically StochKit and PyURDME) from executing.  The workaround is to disable SIP.  One example of how to do this is here: http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

**Comment by aviral26** [comment]
With the move to Docker, this issue should be resolved.

**Comment by ahellander** [comment]
Make sure to document that this is still an issue if you try to run it natively from the GitHub repo, or using older versions of StochSS.

**Comment by aviral26** [comment]
Sure

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/pull/546
