### ISSUE TITLE
Volume rendering times

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#543]
Volume rendering isn't working with fractional timepoints

**Comment by bbbales2** [comment]
Wow, 13 days? I sure was slow on this. Should be fixed: https://github.com/StochSS/stochss/commit/fab3c539bf01c5d9dc993536d8672009576f2332

**Comment by briandrawert** [comment]
I am still seeing errors.  
(1) I got the "error retrieving time series data" message
(2) The "end time" is 1.1, but I specified from 0-1 by 0.1 when I ran the simulation.

![ss1](https://cloud.githubusercontent.com/assets/1413538/13436202/fb15908c-df92-11e5-8a84-bc9a443ea8f5.png)

**Comment by bbbales2** [comment]
Fixed: https://github.com/StochSS/stochss/commit/0c225c8dffd1f62fefaf67c798bddb6892819886

**Comment by briandrawert** [comment]
Works!
